name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - name: Build & publish Mac
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run build:electron:mac -- --publish always

  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - name: Build & publish Windows
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run build:electron:win -- --publish always
